version: '3.8'

services:
  frontend:
    image: "akara4ok/pen2text_frontend"
    ports:
      - "81:80"

  backend:
    image: "akara4ok/pen2text"
    volumes:
      - ./backend/Models:/app/Models
      - ./backend/Data/SpellCorrection:/app/Data/SpellCorrection
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "5000:5000"